remove jBPM 5.3 test jar
This was causing an exception (abbreviated version below) when deploying
to an application server configured with PostgreSQL data sources.
Removing it fixed the error, and I think I have seen (but cannot now
find) advice saying that it should not be deployed.

---

19:14:50,519 ERROR [org.jboss.msc.service.fail] (ServerService Thread
Pool -- 91) MSC000001: Failed to start service
jboss.persistenceunit."cms-portal-services.ear#org.jbpm.persistence.jpa":
org.jboss.msc.service.StartException in service
jboss.persistenceunit."cms-portal-services.ear#org.jbpm.persistence.jpa":
javax.persistence.PersistenceException: [PersistenceUnit:
org.jbpm.persistence.jpa] Unable to build Hibernate SessionFactory

Caused by: javax.persistence.PersistenceException: [PersistenceUnit:
org.jbpm.persistence.jpa] Unable to build Hibernate SessionFactory

Caused by: org.hibernate.tool.schema.spi.SchemaManagementException:
Unable to execute schema management to JDBC target [create table
BooleanExpression (id bigint not null, expression clob, type
varchar(255), Escalation_Constraints_Id bigint, primary key (id))]

Caused by: org.postgresql.util.PSQLException: ERROR: type "clob" does
not exist